WHICH_KEY_ENABLED = false

require("config.animations")
require("config.binds")
require("config.cursor")
require("config.debug")
require("config.decoration")
require("config.devices")
require("config.ecosystem")
require("config.general")
require("config.group")
require("config.input")
require("config.misc")
require("config.monitors")
require("config.permissions")
require("config.startup")
require("config.xwayland")
