local theme = "main"

require("themes/".. theme)
require("monitors")
require("applications")


hl.on("hyprland.start", function()
  hl.exec_cmd("exec uwsm finalize")
  hl.exec_cmd("docker ps") -- HACK
  hl.exec_cmd("paplay \"$HOME/public/audio/windows95-startup.wav\"")
  hl.exec_cmd("uwsm app -S both -- eww open-many main-bar second-bar " .. EWW_INDICATORS .. EWW_QUICK_SETTINGS)
  hl.exec_cmd("hyprpm reload")
end)

require("config/animations")
require("config/binds")
require("config/cursor")
require("config/debug")
require("config/decoration")
require("config/devices")
require("config/ecosystem")
require("config/general")
require("config/group")
require("config/input")
require("config/misc")
require("config/permissions")
require("config/xwayland")

require("layouts")

require("keys/core")
require("keys/leader")
require("keys/mouse")

require("rules/applications/emacs")
require("rules/applications/games")
require("rules/applications/mini-visualizer")
require("rules/applications/mpv")
require("rules/applications/okular")
require("rules/applications/scrcpy")
require("rules/applications/thunderbird")
require("rules/applications/virtmanager")
require("rules/applications/wofi")
require("rules/layers/eww")
require("rules/layers/notifications")
require("rules/layers/wofi")
require("rules/idle-inhibit")
require("rules/windows")
require("rules/workspaces")
