local theme = "main"

require("themes/".. theme)
require("monitors")
require("applications")

require("config/startup")
require("config/animations")
require("config/binds")
require("config/cursor")
require("config/debug")
require("config/decoration")
require("config/devices")
require("config/ecosystem")
require("config/general")
require("config/group")
require("config/input")
require("config/misc")
require("config/permissions")
require("config/xwayland")

require("layouts")

require("keys/core")
require("keys/leader")
require("keys/mouse")

require("rules/applications/emacs")
require("rules/applications/games")
require("rules/applications/mini-visualizer")
require("rules/applications/mpv")
require("rules/applications/okular")
require("rules/applications/scrcpy")
require("rules/applications/thunderbird")
require("rules/applications/virtmanager")
require("rules/applications/wofi")
require("rules/layers/eww")
require("rules/layers/notifications")
require("rules/layers/wofi")
require("rules/idle-inhibit")
require("rules/windows")
require("rules/workspaces")
