hl.define_submap("games", function()

  hl.bind("d" , hl.dsp.exec_cmd(GZDOOM)   , { description = "gzdoom" })
  hl.bind("f" , hl.dsp.exec_cmd(FHEROES2) , { description = "fheroes2 (homm2)" })
  -- hl.bind("g" , hl.dsp.exec_cmd(GAMEHUB)  , { description = "gamehub" })
  hl.bind("h" , hl.dsp.exec_cmd(HEROIC)   , { description = "heroic" })
  hl.bind("l" , hl.dsp.exec_cmd(LUTRIS)   , { description = "lutris" })
  hl.bind("n" , hl.dsp.exec_cmd(NEXUS)    , { description = "Nexus Mods App" })
  hl.bind("s" , hl.dsp.exec_cmd(STEAM)    , { description = "steam" })
  hl.bind("v" , hl.dsp.exec_cmd(VCMI)     , { description = "vcmi (homm3)" })
  hl.bind("x" , hl.dsp.exec_cmd(NEXUS)    , { description = "Nexus Mods App" })

  hl.bind("backspace", function()
    hl.dispatch(hl.dsp.exec_cmd(EWW_SCRIPTS  .. "/which-key.sh -p 'M-o-' open"))
    hl.dispatch(hl.dsp.submap("open"))
  end)

  hl.bind("escape" , RESET_SUBMAP , { release = true })
  hl.bind("d"      , RESET_SUBMAP , { release = true })
  hl.bind("f"      , RESET_SUBMAP , { release = true })
  -- hl.bind("g"      , reset_submap , { release = true })
  hl.bind("h"      , RESET_SUBMAP , { release = true })
  hl.bind("l"      , RESET_SUBMAP , { release = true })
  hl.bind("n"      , RESET_SUBMAP , { release = true })
  hl.bind("s"      , RESET_SUBMAP , { release = true })
  hl.bind("v"      , RESET_SUBMAP , { release = true })
  hl.bind("x"      , RESET_SUBMAP , { release = true })
end)
