hl.bind("SUPER + d", function()
  hl.dispatch(hl.dsp.exec_cmd(EWW_SCRIPTS .. "/which-key.sh -p 'M-d-' dm-global"))
  hl.dispatch(hl.dsp.submap("dm-global"))
end)

hl.define_submap("dm-global", function()
  hl.bind("backslash"       , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-notify")    , { description = "dm-notify" })
  hl.bind("a"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-audio")     , { description = "dm-audio" })
  hl.bind("b"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-bookman")   , { description = "dm-bookman" })
  -- hl.bind("SUPER + d"       , hl.dsp.exec_cmd(myDMScript .. "/dm-master")    , { description = "dm-master" })
  hl.bind("k"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-keys")      , { description = "dm-keys" })
  hl.bind("n"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-notify")    , { description = "dm-notify" })
  hl.bind("p"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-player")    , { description = "dm-player" })
  hl.bind("r"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-record")    , { description = "dm-record" })
  hl.bind("s"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-screenshot"), { description = "dm-screenshot" })
  hl.bind("t"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-theme")     , { description = "dm-theme" })
  hl.bind("w"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-wallpaper") , { description = "dm-wallpaper" })
  hl.bind("z"               , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power")     , { description = "dm-power" })

  hl.bind("catchall"  , RESET_SUBMAP, { release = true })
  hl.bind("backslash" , RESET_SUBMAP, { release = true })
  hl.bind("a"         , RESET_SUBMAP, { release = true })
  hl.bind("b"         , RESET_SUBMAP, { release = true })
  -- hl.bind("SUPER + d" , reset_submap, { release = true })
  hl.bind("k"         , RESET_SUBMAP, { release = true })
  hl.bind("n"         , RESET_SUBMAP, { release = true })
  hl.bind("p"         , RESET_SUBMAP, { release = true })
  hl.bind("r"         , RESET_SUBMAP, { release = true })
  hl.bind("s"         , RESET_SUBMAP, { release = true })
  hl.bind("t"         , RESET_SUBMAP, { release = true })
  hl.bind("w"         , RESET_SUBMAP, { release = true })
  hl.bind("z"         , RESET_SUBMAP, { release = true })
end)
