hl.bind("SUPER + o", switch_submap("M-o-", "open"))

hl.define_submap("open", function()

  hl.bind("b"         , hl.dsp.exec_cmd(SYS_BLUETOOTH)                                                                                   , { description = "bluetooth" })
  hl.bind("c"         , hl.dsp.exec_cmd(COLOR_PICKER)                                                                                    , { description = "color picker" })
  hl.bind("d"         , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'chats' $myDiscordClass $myDiscord")               , { description = "toggle chats" })
  hl.bind("e"         , hl.dsp.exec_cmd("myEmail")                                                                                       , { description = "email client" })

  require("keys.core.open.games")
  hl.bind("g"         , switch_submap("M-o g-", "games"))

  hl.bind("i"         , hl.dsp.exec_cmd("vimiv $XDG_PICTURES_DIR")                                                                       , { description = "image viewer" })
  hl.bind("m"         , hl.dsp.exec_cmd(MUSIC_CLI)                                                                                       , { description = "music player" })
  hl.bind("SHIFT + M" , hl.dsp.exec_cmd(MUSIC_CLI, { workspace = 9, no_initial_focus = true })                                           , { description = "music player on default workspace" })
  hl.bind("t"         , hl.dsp.exec_cmd(BROWSER_TOR)                                                                                     , { description = "tor browser" })
  hl.bind("v"         , hl.dsp.exec_cmd(SYS_AUDIO)                                                                                       , { description = "volume control" })
  hl.bind("w"         , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'chats' 'whatsapp-for-linux' 'whatsapp-for-linux'"), { description = "toggle whatsapp" })

  hl.bind("b"         , RESET_SUBMAP)
  hl.bind("c"         , RESET_SUBMAP)
  hl.bind("d"         , RESET_SUBMAP)
  hl.bind("e"         , RESET_SUBMAP)
  hl.bind("i"         , RESET_SUBMAP)
  hl.bind("m"         , RESET_SUBMAP)
  hl.bind("SHIFT + M" , RESET_SUBMAP)
  hl.bind("t"         , RESET_SUBMAP)
  hl.bind("v"         , RESET_SUBMAP)
  hl.bind("w"         , RESET_SUBMAP)
  hl.bind("catchall"  , RESET_SUBMAP, { release = true })
end)
