hl.bind("SUPER + z", function()
  hl.dispatch(hl.dsp.exec_cmd(EWW_SCRIPTS .. "/which-key.sh -p 'M-z-' dm-power"))
  hl.dispatch(hl.dsp.submap("dm-power"))
end)

hl.define_submap("dm-power", function()
  hl.bind("c"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power controller")         , { description = "disconnect all controllers" })
  hl.bind("l"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power lock")               , { description = "lock screen" })
  hl.bind("SHIFT + L"      , hl.dsp.exec_cmd("loginctl terminate-session'$XDG_SESSION_ID'"), { description = "logout" })
  hl.bind("p"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power poweroff")           , { description = "shutdown system" })
  hl.bind("r"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power reboot")             , { description = "reboot system" })
  hl.bind("s"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power suspend")            , { description = "suspend system" })
  hl.bind("z"              , hl.dsp.exec_cmd(DM_SCRIPTS .. "/dm-power suspend")            , { description = "suspend system" })
  -- hl.bind("SUPER + z"      , hl.dsp.exec_cmd(myDMScript .. "/dm-power suspend")            , { description = "suspend system" })

  hl.bind("catchall"  , RESET_SUBMAP, { release = true })
  hl.bind("c"         , RESET_SUBMAP, { release = true })
  hl.bind("l"         , RESET_SUBMAP, { release = true })
  hl.bind("SHIFT + L" , RESET_SUBMAP, { release = true })
  hl.bind("p"         , RESET_SUBMAP, { release = true })
  hl.bind("r"         , RESET_SUBMAP, { release = true })
  hl.bind("s"         , RESET_SUBMAP, { release = true })
  hl.bind("z"         , RESET_SUBMAP, { release = true })
  -- hl.bind("SUPER + z" , reset_submap, { release = true })
end)
