hl.bind("SUPER + s", switch_submap("M-s-", "scratchpad"))

hl.define_submap("scratchpad", function()
  hl.bind("a"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'anki' 'anki' 'anki'")                                          , { description = "anki" })
  hl.bind("b"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'bluetooth' " .. SYS_BLUETOOTH .. SYS_BLUETOOTH)              , { description = "bluetooth" })
  hl.bind("c"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'calculator' 'org.gnome.Calculator' 'gnome-calculator'")        , { description = "calculator" })
  hl.bind("d"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'chats' " .. DISCORD_CLASS .. DISCORD)                       , { description = "discord" })
  hl.bind("e"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'email' " .. EMAIL_CLASS .. EMAIL)                           , { description = "email client" })
  hl.bind("m"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'music' 'sp-music' 'alacritty --class sp-music -e ncmpcpp'")    , { description = "music player" })
  hl.bind("p"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'phone' 'scrcpy' 'scrcpy'")                                     , { description = "phone" })
  hl.bind("t"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'torrent' 'com.transmissionbt.transmission' 'transmission-gtk'"), { description = "torrent" })
  hl.bind("v"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'vm' 'virt-manager' 'virt-manager'")                            , { description = "vm" })
  hl.bind("w"                , hl.dsp.exec_cmd(HYPR_SCRIPTS .. "/toggle-special-workspace.sh 'chats' 'whatsapp-for-linux' 'whatsapp-for-linux'")             , { description = "whatsapp" })

  hl.bind("a"       , RESET_SUBMAP)
  hl.bind("b"       , RESET_SUBMAP)
  hl.bind("c"       , RESET_SUBMAP)
  hl.bind("d"       , RESET_SUBMAP)
  hl.bind("e"       , RESET_SUBMAP)
  hl.bind("m"       , RESET_SUBMAP)
  hl.bind("p"       , RESET_SUBMAP)
  hl.bind("t"       , RESET_SUBMAP)
  hl.bind("v"       , RESET_SUBMAP)
  hl.bind("w"       , RESET_SUBMAP)
  hl.bind("catchall", RESET_SUBMAP, { release = true })
end)
