-- focus
hl.bind("SUPER + tab", hl.dsp.focus({ workspace = "previous" , on_current_monitor = true }) , { description = "toggle last workspace" })
hl.bind("SUPER + 1"  , hl.dsp.focus({ workspace = 1          , on_current_monitor = true }) , { description = "switch to workspace 1" })
hl.bind("SUPER + 2"  , hl.dsp.focus({ workspace = 2          , on_current_monitor = true }) , { description = "switch to workspace 2" })
hl.bind("SUPER + 3"  , hl.dsp.focus({ workspace = 3          , on_current_monitor = true }) , { description = "switch to workspace 3" })
hl.bind("SUPER + 4"  , hl.dsp.focus({ workspace = 4          , on_current_monitor = true }) , { description = "switch to workspace 4" })
hl.bind("SUPER + 5"  , hl.dsp.focus({ workspace = 5          , on_current_monitor = true }) , { description = "switch to workspace 5" })
hl.bind("SUPER + 6"  , hl.dsp.focus({ workspace = 6          , on_current_monitor = true }) , { description = "switch to workspace 6" })
hl.bind("SUPER + 7"  , hl.dsp.focus({ workspace = 7          , on_current_monitor = true }) , { description = "switch to workspace 7" })
hl.bind("SUPER + 8"  , hl.dsp.focus({ workspace = 8          , on_current_monitor = true }) , { description = "switch to workspace 8" })
hl.bind("SUPER + 9"  , hl.dsp.focus({ workspace = 9          , on_current_monitor = true }) , { description = "switch to workspace 9" })
hl.bind("SUPER + 0"  , hl.dsp.focus({ workspace = 10         , on_current_monitor = true }) , { description = "switch to workspace 10" })

-- moving windows
hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1  , follow = false }), { description = "move window to workspace 1" })
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2  , follow = false }), { description = "move window to workspace 2" })
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3  , follow = false }), { description = "move window to workspace 3" })
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4  , follow = false }), { description = "move window to workspace 4" })
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5  , follow = false }), { description = "move window to workspace 5" })
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6  , follow = false }), { description = "move window to workspace 6" })
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7  , follow = false }), { description = "move window to workspace 7" })
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8  , follow = false }), { description = "move window to workspace 8" })
hl.bind("SUPER + SHIFT + 9", hl.dsp.window.move({ workspace = 9  , follow = false }), { description = "move window to workspace 9" })
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = 10 , follow = false }), { description = "move window to workspace 10" })

-- moving windows with switching workspace
hl.bind("SUPER + SHIFT + CTRL + 1", hl.dsp.window.move({ workspace = 1  }), { description = "move window to workspace 1 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 2", hl.dsp.window.move({ workspace = 2  }), { description = "move window to workspace 2 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 3", hl.dsp.window.move({ workspace = 3  }), { description = "move window to workspace 3 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 4", hl.dsp.window.move({ workspace = 4  }), { description = "move window to workspace 4 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 5", hl.dsp.window.move({ workspace = 5  }), { description = "move window to workspace 5 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 6", hl.dsp.window.move({ workspace = 6  }), { description = "move window to workspace 6 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 7", hl.dsp.window.move({ workspace = 7  }), { description = "move window to workspace 7 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 8", hl.dsp.window.move({ workspace = 8  }), { description = "move window to workspace 8 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 9", hl.dsp.window.move({ workspace = 9  }), { description = "move window to workspace 9 with switch"  })
hl.bind("SUPER + SHIFT + CTRL + 0", hl.dsp.window.move({ workspace = 10 }), { description = "move window to workspace 10 with switch" })
